// Code generated by protoc-gen-go-ext. DO NOT EDIT.
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pkg/event/pb/reponse.proto

package event

import (
	proto "github.com/golang/protobuf/proto"
	event "github.com/infraboard/mcube/bus/event"
	_ "github.com/infraboard/protoc-gen-go-ext/extension/tag"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// OperateEventSet todo
type OperateEventSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Items []*event.OperateEvent `protobuf:"bytes,2,rep,name=items,proto3" json:"items"`
}

func (x *OperateEventSet) Reset() {
	*x = OperateEventSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_event_pb_reponse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateEventSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateEventSet) ProtoMessage() {}

func (x *OperateEventSet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_event_pb_reponse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateEventSet.ProtoReflect.Descriptor instead.
func (*OperateEventSet) Descriptor() ([]byte, []int) {
	return file_pkg_event_pb_reponse_proto_rawDescGZIP(), []int{0}
}

func (x *OperateEventSet) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OperateEventSet) GetItems() []*event.OperateEvent {
	if x != nil {
		return x.Items
	}
	return nil
}

type SaveReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success []string `protobuf:"bytes,1,rep,name=success,proto3" json:"success"`
	Failed  []string `protobuf:"bytes,2,rep,name=failed,proto3" json:"failed"`
}

func (x *SaveReponse) Reset() {
	*x = SaveReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_event_pb_reponse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveReponse) ProtoMessage() {}

func (x *SaveReponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_event_pb_reponse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveReponse.ProtoReflect.Descriptor instead.
func (*SaveReponse) Descriptor() ([]byte, []int) {
	return file_pkg_event_pb_reponse_proto_rawDescGZIP(), []int{1}
}

func (x *SaveReponse) GetSuccess() []string {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *SaveReponse) GetFailed() []string {
	if x != nil {
		return x.Failed
	}
	return nil
}

var File_pkg_event_pb_reponse_proto protoreflect.FileDescriptor

var file_pkg_event_pb_reponse_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x72,
	0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x3f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67,
	0x6f, 0x2d, 0x65, 0x78, 0x74, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f,
	0x74, 0x61, 0x67, 0x2f, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x30, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2f, 0x6d, 0x63, 0x75, 0x62, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x80, 0x01, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x42, 0x12, 0xc2, 0xde, 0x1f, 0x0e, 0x0a, 0x0c, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x43, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d,
	0x63, 0x75, 0x62, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x12, 0xc2, 0xde, 0x1f, 0x0e, 0x0a, 0x0c, 0x6a,
	0x73, 0x6f, 0x6e, 0x3a, 0x22, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0x6a, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x42, 0x14, 0xc2, 0xde, 0x1f, 0x10, 0x0a, 0x0e, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x2b, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x42, 0x13, 0xc2, 0xde, 0x1f, 0x0f, 0x0a, 0x0d, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22, 0x66,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x22, 0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x42, 0x2a,
	0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_event_pb_reponse_proto_rawDescOnce sync.Once
	file_pkg_event_pb_reponse_proto_rawDescData = file_pkg_event_pb_reponse_proto_rawDesc
)

func file_pkg_event_pb_reponse_proto_rawDescGZIP() []byte {
	file_pkg_event_pb_reponse_proto_rawDescOnce.Do(func() {
		file_pkg_event_pb_reponse_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_event_pb_reponse_proto_rawDescData)
	})
	return file_pkg_event_pb_reponse_proto_rawDescData
}

var file_pkg_event_pb_reponse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_event_pb_reponse_proto_goTypes = []interface{}{
	(*OperateEventSet)(nil),    // 0: eventbox.event.OperateEventSet
	(*SaveReponse)(nil),        // 1: eventbox.event.SaveReponse
	(*event.OperateEvent)(nil), // 2: mcube.event.OperateEvent
}
var file_pkg_event_pb_reponse_proto_depIdxs = []int32{
	2, // 0: eventbox.event.OperateEventSet.items:type_name -> mcube.event.OperateEvent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_event_pb_reponse_proto_init() }
func file_pkg_event_pb_reponse_proto_init() {
	if File_pkg_event_pb_reponse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_event_pb_reponse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateEventSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_event_pb_reponse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_event_pb_reponse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_event_pb_reponse_proto_goTypes,
		DependencyIndexes: file_pkg_event_pb_reponse_proto_depIdxs,
		MessageInfos:      file_pkg_event_pb_reponse_proto_msgTypes,
	}.Build()
	File_pkg_event_pb_reponse_proto = out.File
	file_pkg_event_pb_reponse_proto_rawDesc = nil
	file_pkg_event_pb_reponse_proto_goTypes = nil
	file_pkg_event_pb_reponse_proto_depIdxs = nil
}
