// Code generated by protoc-gen-go-http. DO NOT EDIT.

package event

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:         "/eventbox.event.Service/SaveEvent",
				FunctionName:     "SaveEvent",
				Path:             "/events/",
				Method:           "POST",
				Resource:         "event",
				AuthEnable:       true,
				PermissionEnable: true,
				AuditLog:         false,
				Labels:           map[string]string{"action": "create"},
			},
			{
				GrpcPath:         "/eventbox.event.Service/QueryEvent",
				FunctionName:     "QueryEvent",
				Path:             "/events/",
				Method:           "GET",
				Resource:         "event",
				AuthEnable:       false,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{},
			},
		},
	}
	return set
}
